#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""
import sys


def factorize_num():
    """
    Function look for file and factorize numbers into two prime numbers
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line in f:
                line = int(line)
                if line % 2 == 0:
                    print("{}={}*{}".format(line, line // 2, 2))
                    continue
                i = 3
                while i < line // 2:
                    if line % i == 0:
                        print("{}={}*{}".format(line, line // i, i))
                        break
                    i = i + 2
                if i == (line // 2) + 1:
                    print("{}={}*{}".format(line, line, 1))
    except (IndexError):
        pass
